import Head from "next/head";
import AppLayout from "@/components/Layouts/AppLayout";
import { wrapper } from "@/store";
import { Button, Card } from "flowbite-react";
import DataTable from 'react-data-table-component';
import NavLink from "@/components/NavLink";
import { useRouter } from "next/router";
import Actions from "@/components/Actions";
import { useEffect, useState } from "react";
import { toast } from "react-toastify";
import {
    getPurchaseRequisition,
    useDestroyPurchaseRequisitionMutation,
    useGetPurchaseRequisitionQuery,
    getRunningQueriesThunk
} from "@/store/service/requisitions/purchase";

const PurchaseRequisition = () => {
    const router = useRouter();
    const {data, isLoading, isError} = useGetPurchaseRequisitionQuery();
    const [destroy, destroyResponse] = useDestroyPurchaseRequisitionMutation();
    const [columns, setColumns] = useState([]);


    useEffect(() => {
        if (!destroyResponse.isLoading && destroyResponse.isSuccess){
            toast.success('Options deleted.')
        }
    }, [destroyResponse])
    useEffect(() => {
        if (!isLoading && !isError && data){
            setColumns([
                {
                    name: 'I.R.F. No.',
                    selector: row => row.irf_no,
                    sortable: true,
                },
                {
                    name: 'Total Req. Unit',
                    selector: row => row.total_required_unit,
                    sortable: true,
                },
                {
                    name: 'Department',
                    selector: row => row.department?.name,
                    sortable: true,
                },
                {
                    name: 'Estimated Cost',
                    selector: row => parseFloat(row.estimated_total_amount).toLocaleString(),
                    sortable: true,
                },
                {
                    name: 'Generated By',
                    selector: row => row.user?.name,
                    sortable: true,
                },
                {
                    name: 'Created at',
                    selector: row => row.created_at,
                    sortable: true,
                },
                {
                    name: 'Actions',
                    cell: (row) => <Actions
                        itemId={row.id}
                        edit={`/purchase-requisition/${row.id}/edit`}
                        view={`/purchase-requisition/${row.id}/view`}
                        destroy={destroy}
                        progressing={destroyResponse.isLoading}
                    />,
                    ignoreRowClick: true,
                }
            ]);
        }
    }, [isLoading, isError, data]);


    return (
        <>
            <Head>
                <title>Purchase Requisition</title>
            </Head>
            <AppLayout
                header={
                    <h2 className="font-semibold text-xl text-gray-800 leading-tight">
                        Purchase Requisition.
                    </h2>
                }
            >
                <Head>
                    <title>Purchase Requisition.</title>
                </Head>
                <div className="md:py-8 md:mx-16 mx-0 md:px-4 sm:px-6 lg:px-8">
                    <Card>
                        <div className="flex flex-row space-x-4 space-y-4 shadow-lg py-4 px-4">
                            <NavLink
                                active={router.pathname === 'purchase-requisition/create'}
                                href={`purchase-requisition/create`}
                            >
                                <Button>Create</Button>
                            </NavLink>
                        </div>
                        <DataTable
                            columns={columns}
                            data={data?.data}
                            pagination
                            responsive
                            progressPending={isLoading}
                            persistTableHead
                        />
                    </Card>
                </div>
            </AppLayout>
        </>
    )
}

export const getServerSideProps = wrapper.getServerSideProps((store) => async (context) => {
    // const params = context.params
    store.dispatch(getPurchaseRequisition.initiate())
    await Promise.all(store.dispatch(getRunningQueriesThunk()));
    return {
        props: {},
    };
})

export default PurchaseRequisition;
